image: debian/buster
packages:
    - pkg-config
    - curl
    - libssl-dev
    # - cargo
sources:
 - hg+https://hg.sr.ht/~icefox/garnet
secrets:
 - f217b06a-9ade-4b5f-825a-cc377a9188ee
tasks:
 - setup: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    sh rustup.sh -y -q
    source .cargo/env
    cargo install cargo-tarpaulin
 - build: |
    source .cargo/env
    cd garnet
    cargo build
 - test: |
    source .cargo/env
    cd garnet
    cargo test
 - coverage: |
    source .cargo/env
    cd garnet
    cargo tarpaulin
    scp tarpaulin-report.html icefox@roc.alopex.li:htdocs/temp/

