image: debian/bullseye
packages:
    - pkg-config
    - curl
    - libssl-dev
    - cargo
sources:
 - hg+https://hg.sr.ht/~icefox/garnet
secrets:
 - 384fc780-f42a-4945-854e-cbd952d6802b
tasks:
 - setup: |
    cargo install cargo-tarpaulin
 - build: |
    cd garnet
    cargo build
 - test: |
    cd garnet
    cargo test
 - coverage: |
    cd garnet
    cargo tarpaulin -o Html
    scp -o StrictHostKeyChecking=no tarpaulin-report.html icefox@roc.alopex.li:htdocs/temp/

