image: debian/buster
packages:
    - pkg-config
    - curl
    - libssl-dev
    # - cargo
sources:
 - hg+https://hg.sr.ht/~icefox/garnet
secrets:
 - 384fc780-f42a-4945-854e-cbd952d6802b
tasks:
 - setup: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    sh rustup.sh -y -q
    source .cargo/env
    cargo install cargo-tarpaulin
 - build: |
    source .cargo/env
    cd garnet
    cargo build
 - test: |
    source .cargo/env
    cd garnet
    cargo test
 - coverage: |
    source .cargo/env
    cd garnet
    cargo tarpaulin -o Html
    scp -o StrictHostKeyChecking=no tarpaulin-report.html icefox@roc.alopex.li:htdocs/temp/

