[package]
name = "garnet"
version = "0.1.0"
authors = ["Simon Heath <icefox@dreamquest.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[dependencies]
walrus = {version = "0.17", default-features = false}
logos = "0.11"
pico-args = "0.3"

[dev-dependencies]
# Use wasmtime to evaluate results of end-to-end tests.
wasmtime = "0.16"
