[package]
name = "garnet"
version = "0.1.0"
authors = ["Simon Heath <icefox@dreamquest.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-builder = { git = "https://github.com/JCapucho/wasm-builder.git" }
walrus = {version = "0.17", default-features = false}
logos = "0.11"

[dev-dependencies]
# Use wasmtime to evaluate results of end-to-end tests.
wasmtime = "0.16"
