[package]
name = "garnet"
version = "0.1.0"
authors = ["Simon Heath <icefox@dreamquest.io>"]
edition = "2018"

[dependencies]
walrus = {version = "0.17", default-features = false}
logos = "0.11"
gumdrop = "0.8"

[dev-dependencies]
# Use wasmtime to evaluate results of end-to-end tests.
wasmtime = "0.16"
